export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const FETCH_LOGIN_DETAIL_REQUESTED = 'FETCH_LOGIN_DETAIL_REQUESTED';
export const FETCH_LOGIN_DETAIL_SUCCEEDED = 'FETCH_LOGIN_DETAIL_SUCCEEDED';

export const RENDER_LOGIN_FORM_REQUESTED = 'RENDER_LOGIN_FORM_REQUESTED';

export const renderLoginForm = payload => {
  return {
    type: RENDER_LOGIN_FORM_REQUESTED,
    data: payload
  };
};
