export const FORGOT_PASSWORD_REQUESTED = 'FORGOT_PASSWORD_REQUESTED';
export const FORGOT_PASSWORD_SUCCEEDED = 'FORGOT_PASSWORD_SUCCEEDED';

export const FORGOT_PASSWORD_FAILEDED = 'FORGOT_PASSWORD_FAILEDED';

export const RENDER_FORGOT_PASSWORD_FORM_REQUESTED = 'RENDER_FORGOT_PASSWORD_FORM_REQUESTED';

export const renderForgotPasswordForm = payload => {
  return {
    type: RENDER_FORGOT_PASSWORD_FORM_REQUESTED,
    data: payload
  };
};
